# Generated by Django 5.1.2 on 2025-03-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gradecurricular_componentecurricular_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='pode_alterar',
            field=models.ManyToManyField(blank=True, related_name='can_edit_alocacao', to='api.user'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='pode_compartilhar',
            field=models.ManyToManyField(blank=True, related_name='can_share_alocacao', to='api.user'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='pode_alterar',
            field=models.ManyToManyField(blank=True, related_name='can_edit_grade_curricular', to='api.user'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='pode_compartilhar',
            field=models.ManyToManyField(blank=True, related_name='can_share_grade_curricular', to='api.user'),
        ),
        migrations.AddField(
            model_name='horario',
            name='pode_alterar',
            field=models.ManyToManyField(blank=True, related_name='can_edit_horario', to='api.user'),
        ),
        migrations.AddField(
            model_name='horario',
            name='pode_compartilhar',
            field=models.ManyToManyField(blank=True, related_name='can_share_horario', to='api.user'),
        ),
    ]
