version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_dist:/frontend/dist
    ports:
      - "5173:5173"
  nginx:
    build: 
      context: ./nginx
    ports:
      - 8080:80
    volumes:
      - frontend_dist:/var/www/html
    depends_on:
      - backend
      - frontend

volumes:
  frontend_dist:
  postgres_data: